DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS missions CASCADE;
DROP TABLE IF EXISTS progress CASCADE;
CREATE TABLE users (
    id SERIAL PRIMARY KEY NOT NULL,
    name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL
);
CREATE TABLE missions (
    id SERIAL PRIMARY KEY NOT NULL,
    name VARCHAR(255) NOT NULL
);
CREATE TABLE progress (
    id SERIAL PRIMARY KEY NOT NULL,
    user_id INTEGER REFRENCES users(id),
    mission_id INTEGER REFERENCES missions(id),
    completed BOOLEAN
);